name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: compose build
        run: docker compose up --build

      - name: Verify deployment
        run: |
          sleep 5
          curl http://localhost:3000