name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: building the app
        run: |
          touch file1
          echo "app is build" > file1

  deploy:
    runs-on: self-hosted

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: compose build
        run: docker compose up --build -d

      - name: Verify deployment
        run: |
          sleep 5
          curl http://localhost:3000